app/ios/Runner.xcodeproj/project.pbxproj
None
- Sync Development, Deploy Provisioning Files
=> Feature - Sync IPhone Development Files

app/lib/bindings/profile_binding.dart, app/lib/models/profile/weekly_calendar_state.dart, app/lib/view_models/profile/profile_view_model.dart, app/lib/view_models/profile/weekly_calendar_view_model.dart, app/lib/views/profile/profile_screen.dart, app/lib/views/profile/widgets/custom_carbon_bar_chart.dart, app/lib/views/profile/widgets/user_history.dart, app/lib/views/profile/widgets/user_profile.dart, app/lib/views/profile/widgets/weekly_calendar.dart, app/pubspec.yaml
- Resolves : #20 
- Create Weekly Calendar
- Create Custom Bar Chart
- Create List view about user history
=> ⚡ Feature - My Page Screen v2

app/lib/apps/main_app.dart, app/lib/bindings/init_binding.dart, app/lib/domains/dao/action_history_dao.dart, app/lib/domains/dao/user_dao.dart, app/lib/domains/type/e_challenge.dart, app/lib/main.dart, app/lib/models/load_map/challenge_history_state.dart, app/lib/providers/action/action_history_local_provider.dart, app/lib/repositories/action_history_repository.dart, app/lib/repositories/challenge_history_repository.dart, app/lib/repositories/user_repository.dart, app/lib/utilities/translation/app_translations.dart, app/lib/utilities/translation/common_translations.dart, app/lib/utilities/translation/e_challenge_translations.dart, app/lib/view_models/home/home_view_model.dart, app/lib/view_models/load_map/load_map_view_model.dart, app/lib/view_models/profile/profile_view_model.dart, app/lib/views/load_map/widgets/challenge_history_item.dart, app/lib/widgets/dialog/challenge_dialog.dart
- Resolves : #44
- Change Variable Name
- Async DI(Repository, Provider)
- Apply Pagination Action History
=> 🎨 Refacto - Memory Optimization

.github/CODEOWNERS, .github/pull_request_template.md
- Deploy Server(FaaS) Version 1.1.0
=> 🚀 Deploy - Server(FaaS) Version 1.1.0

app/lib/providers/follow/follow_provider_impl.dart, app/lib/repositories/user_repository.dart, app/lib/views/setting/widgets/custom_time_picker_dialog.dart, app/pubspec.yaml
- Change List To Map(Sorting Error)
=> 🐛 Fix - Follow PreProcessing Error

app/lib/utilities/functions/notification_util.dart, app/lib/utilities/translation/app_translations.dart
- Fix Notification Content tr Error
=> 🐛 fix: Notification Content Error

app/pubspec.yaml
- pubspec version 1.1.3+1 -> 1.1.3+2
=> 🚀 chore - version 1.1.3+1 -> 1.1.3+2

README.md
- Resolves : #51 
- Update README.md
=> ⚡ Docs - Update README.md

app/README.md
- Resolves : #59 
- App Directory README.md
=> 📝 Documentation - Create App README.md

README.md, app/README.md, app/lib/utilities/functions/notification_util.dart, app/lib/utilities/translation/app_translations.dart, app/pubspec.yaml
- Deploy Version 1.1.3+1 -> 1.1.3+2
=> 🚀 Deploy - Version 1.1.3+2

app/lib/providers/follow/follow_provider_impl.dart, app/lib/utilities/translation/app_translations.dart, app/lib/views/ranking/ranking_screen.dart
- Resolves : #68 
- My Data Sync Error
=> ✨ Fix - Data Sync Error

server/trigger_and_notification_api/functions/index.js, server/trigger_and_notification_api/package-lock.json, server/trigger_and_notification_api/package.json
- Resolves : 
- Token Condition Error
- Message API
=> ✨ 🚑 [ Fix, Feature ] - Token Condition Error, Message API

server/trigger_and_notification_api/functions/index.js
- Resolves : 
- Firebase and Cloud Function Timestamp Sync Error
=> 🚑 Fix - Time Error

app/pubspec.yaml
- Resolves : 
- 1.1.3 -> 1.2.0
=> ✨ Develop - Version Up

app/lib/providers/follow/follow_provider_impl.dart, app/lib/view_models/setting/setting_view_model.dart, app/pubspec.yaml
- Resolves : #75 
- Fix Setting DI Error
- Fix Ranking State Error
=> 🚑 Fix - DI, State Error

app/lib/views/ranking/ranking_screen.dart
- Resolves : #79 
- When on tap Rank Item by mySelf, serving Message Error
=> 🐛 Fix - OnTap Rank Item Error

app/pubspec.yaml
- Resolves : 
- Update Version 1.2.0+3
=> 🚀 Deploy - Change Version 

README.md, app/README.md
- Resolves : #81 
- Update How to run app
- Update Download Android APK
- Update Round2 Demo Video
- Update UI Screen
=> ⚡ Docs - Update README 

server/README.md
- Resolves : #85 
- Update README.md
=> 📝 Docs - Update README.md

server/README.md, server/trigger_and_notification_api/functions/index.js, server/trigger_and_notification_api/package-lock.json, server/trigger_and_notification_api/package.json
- Resolves : 
- Deploy Server 1.2.0
=> 🚀 Deploy - Version 1.2.0
